apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/SethuRamanOmanakuttan/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.3.1
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://10.251.4.130:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secret/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIDKNwuq67KIFhc3EOJK2e9foYe7U49ot22lWUj53TcRrEpZeCpNeCpBeCngKWggBEAEaBgjP
      h4WOBiIKc3lzY2hhbm5lbCpAY2YxZjE3YTRiOTY1NGJlNWQ5MDA4ZThmMzA5OWM0ZTY2OTQ2YmI0
      YmIwZjIwZTU0ZGE2ZWY3OTIzNmE2YTljMRIaEhgE4/a5EyOj9w4NYUnLzKA7X5407/LZ8+sSk10K
      kF0SjV0SiysKB09yZGVyZXIS/yoSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVQTVZb1JoL3dJcXQreW9QQW0zT095TGVlQXhJd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05NakV4TWpJeE1ESTBOVFUxV2hjTk1qUXhNREV3TURJME5UVTFX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJGMFpM
      eGRWRG0wY0lPci96YW5raEVVVmFtSUpNcW92b3g1cllCdlpMTUwrbWgrdE90RmoKWkFhN3RaSzdR
      Wk5Fako2cHBLVm1CZ3NaOFMxeTVKSUZzdFdqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0s3UGVhandiYXpHVG1DbkpodDJhVUJE
      RlIvREFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBazROM2poNlpDRVVDTlorNzZNamZhRmxydzJU
      SGdxcWV3dVVGYS9NVUUKQUFJaEFPMW8xZ2J5d3J2eTQwWFRmMlFOK2pjUkw4eFcraGN3a3dHazlw
      bFR0eHNTCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVWVh5MjBreGNuQ20weGwzL2thR3ZYejI5MW04d0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NakV4TWpJeE1ESTFOREF3V2hjTk1q
      SXhNakl4TURJMU9UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFcUQ0SnFvR3JGeHJ1WEFJdGFiWHJwenF1OS82
      b2xlL2IKSjRaZ205S2p4UVJocFdzQ2g1YkdQaGRoeSt2d0pOeFUvUktITnJ2QTNheHdscE41akRS
      b3FxT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRQUU3Zk9xYjNwCjBuU2hSMEpld3M1NHNlcUtMVEFmQmdOVkhTTUVHREFXZ0JT
      SzdQZWFqd2JhekdUbUNuSmh0MmFVQkRGUi9EQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M04yTTVOR1kyWkdNM0xXUnNjbmcwTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnTjhzeUJmL3F6WmlhNGs0UGFaa2ZFOFlPc3MzdHhSVlZ6VFpsV1pXRVdOQUNJRzB6
      c0VkRzNTaWk2dTJvClZSdkhESjBtY2Q3MGEvajFuMU1IR0JGWkJ4Uk0KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVQTVZb1JoL3dJcXQreW9QQW0zT095TGVlQXhJd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NakV4TWpJeE1ESTBOVFUxV2hjTk1qUXhNREV3
      TURJME5UVTFXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJGMFpMeGRWRG0wY0lPci96YW5raEVVVmFtSUpNcW92b3g1cllCdlpMTUwrbWgrdE90RmoK
      WkFhN3RaSzdRWk5Fako2cHBLVm1CZ3NaOFMxeTVKSUZzdFdqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0s3UGVhandiYXpHVG1D
      bkpodDJhVUJERlIvREFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBazROM2poNlpDRVVDTlorNzZN
      amZhRmxydzJUSGdxcWV3dVVGYS9NVUUKQUFJaEFPMW8xZ2J5d3J2eTQwWFRmMlFOK2pjUkw4eFcr
      aGN3a3dHazlwbFR0eHNTCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMahBIKDUNvbnNlbnN1
      c1R5cGUS8hES5xEKCGV0Y2RyYWZ0EtoRCsMRChpvcmRlcmVyMS5kZXZlbG9wLmxvY2FsLmNvbRD7
      QRrPCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQWpDQ0FxbWdBd0lCQWdJVUFtbTV2
      KzdacVIyeG1aNG92aTRtSmYySkg1RXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNS
      MEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURW
      UVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpI
      aGNOTWpFeE1qSXhNREkxTkRBd1doY05Nakl4TWpJeE1ESTFPVEF3V2pCeE1Rc3dDUVlEVlFRR0V3
      SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3
      ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNt
      VnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3
      TkNBQVNNays5Mm1oUS9SbjNLK0pFL1lLSGVQNzlaCnF6R0hRSTUrNzZiZHBLMHhDWFMyZ1A5d1gz
      TTBBU2xJSlJoVVlJTThPSlB2eG9yNjlId1gzdFV6aHFLU280SUIKTURDQ0FTd3dEZ1lEVlIwUEFR
      SC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJn
      TlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlEyNGp4cDg3aDVUb0RPd1plb3RDUjdZUHhMClp6
      QWZCZ05WSFNNRUdEQVdnQlNLN1BlYWp3YmF6R1RtQ25KaHQyYVVCREZSL0RBL0JnTlZIUkVFT0RB
      MmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1W
      c2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWhtTGtG
      bVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEpsY2pF
      dWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3Q2dZ
      SUtvWkl6ajBFQXdJRFJ3QXdSQUlnWHk1SzRHRGR5dHVkZTVSSwp6TVo3cjgzd3lNczVONTNNQkVO
      VTFyNjVEbDRDSUZRd2FLWHV1OGNEQ3d2MFE4RDRmUkZmVmNqVUcxaFBOMXY5CmpQM3I0R3plCi0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIs8ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SURBakNDQXFtZ0F3SUJBZ0lVQW1tNXYrN1pxUjJ4bVo0b3ZpNG1KZjJKSDVFd0NnWUlLb1pJemow
      RUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1
      emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NakV4TWpJeE1ESTFOREF3V2hjTk1qSXhNakl4TURJ
      MU9UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRN
      dlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21W
      eU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdj
      cWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBU01rKzkybWhRL1JuM0srSkUvWUtIZVA3OVoKcXpH
      SFFJNSs3NmJkcEsweENYUzJnUDl3WDNNMEFTbElKUmhVWUlNOE9KUHZ4b3I2OUh3WDN0VXpocUtT
      bzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVG
      QndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUTI0anhw
      ODdoNVRvRE93WmVvdENSN1lQeEwKWnpBZkJnTlZIU01FR0RBV2dCU0s3UGVhandiYXpHVG1Dbkpo
      dDJhVUJERlIvREEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1
      WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dC
      QkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhz
      YldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3
      WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdYeTVLNEdEZHl0dWRl
      NVJLCnpNWjdyODN3eU1zNU41M01CRU5VMXI2NURsNENJRlF3YUtYdXU4Y0RDd3YwUThENGZSRmZW
      Y2pVRzFoUE4xdjkKalAzcjRHemUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQ
      ChgBIAUogICACBoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4K
      DEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZB
      ZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0I
      AxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMi
      KgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zErsvCgtD
      b25zb3J0aXVtcxKrLxLgLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsYuErsXCg9tYW51ZmFjdHVy
      ZXJNU1ASpxcarxUKA01TUBKnFRKcFRKZFQoPbWFudWZhY3R1cmVyTVNQEoYGLS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUNEVENDQWJLZ0F3SUJBZ0lVUWpJUmJqN2krdHZNT25JaDh5bElJ
      UmVWbk1zd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01C
      bHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpk
      SFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qRXhN
      akl4TURJME56VTNXaGNOTWpReE1ERXdNREkwTnpVM1dqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBN
      QTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpE
      RTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGRE
      QlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCRWZqYnoxU1lPZm05M1doQVlnY3hk
      Lzc1b212TS9WVlRjbDEKeVJ4c1FZdVhHbnlNblZtaGUwb3hWUWw2OWhYY3JjWEVzT3pESVdTZ3hP
      U0NZQldYaG91alFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFn
      R21NQjBHQTFVZERnUVdCQlJadk5RMUNQUW9LdWFZClhidjc5UlA2czJ3eGNEQUtCZ2dxaGtqT1BR
      UURBZ05KQURCR0FpRUExVWY3cDFFcmoreFByZlN3Q3ZMd1RBZWMKT0hScGJuN3MxTmk3cWgwSmtH
      WUNJUUNuRUUwWVpmYkxBaFhmWlFtWkRJbjVscDNBcUR4Ymt6N2xSZmwvNS83agpxUT09Ci0tLS0t
      RU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURF
      VENDQXJlZ0F3SUJBZ0lVWHYvMnJ2eG1icGJ5ZnMxYnJOQXEvZlRldGc0d0NnWUlLb1pJemowRUF3
      SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUy
      TmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qRXhNakl4TURJMU5UQXdXaGNOTWpJeE1q
      SXhNRE13TURBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEzTGpNNEx6
      Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFNQmdOVkJB
      c1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFEREJaQlpH
      MXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkKemowREFR
      Y0RRZ0FFZXBId2wrbEhnTWtlejAzOVNKdkI0WlV0aXg5N0MydnBtdTJWSVlQSWlUT2RTT1lFS3V1
      NQpTRlQwQlhiZkJtOWpKeW1VOUYwZFBVWVV2TFRTSURVVlhxT0NBU0l3Z2dFZU1BNEdBMVVkRHdF
      Qi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJRVTJ4aUdWcnQ2MHQw
      VXIxaTlLSllZc1p0UlBEQWYKQmdOVkhTTUVHREFXZ0JSWnZOUTFDUFFvS3VhWVhidjc5UlA2czJ3
      eGNEQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwNE5UaGpabVEwTnpnNExYWjJObkoyTUlH
      WEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lkSEoxWlNJ
      c0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVkV1poWTNS
      MWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZM1IxY21W
      eUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklBREJG
      CkFpRUE5VldIRUFJbTd5TWQ1VzgyaGZxdytSTUNKbHZoZVFHWEs3NTR1Qy9MMFNzQ0lGZXdqc3gv
      TVFIenUvWU4KaS9XaVQ4Rk1YT0o5b0FKNlVjMHVmbFNwTlM3cAotLS0tLUVORCBDRVJUSUZJQ0FU
      RS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKhgYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJ
      Q0RUQ0NBYktnQXdJQkFnSVVRaklSYmo3aSt0dk1PbkloOHlsSUlSZVZuTXN3Q2dZSUtvWkl6ajBF
      QXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVF
      Qnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1N
      RTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpFeE1qSXhNREkwTnpVM1doY05NalF4
      TURFd01ESTBOelUzV2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05v
      TVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVj
      TUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VH
      Q0NxR1NNNDlBd0VIQTBJQUJFZmpiejFTWU9mbTkzV2hBWWdjeGQvNzVvbXZNL1ZWVGNsMQp5Unhz
      UVl1WEdueU1uVm1oZTBveFZRbDY5aFhjcmNYRXNPekRJV1NneE9TQ1lCV1hob3VqUWpCQU1BOEdB
      MVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUlp2
      TlExQ1BRb0t1YVkKWGJ2NzlSUDZzMnd4Y0RBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQTFVZjdw
      MUVyait4UHJmU3dDdkx3VEFlYwpPSFJwYm43czFOaTdxaDBKa0dZQ0lRQ25FRTBZWmZiTEFoWGZa
      UW1aREluNWxwM0FxRHhia3o3bFJmbC81LzdqCnFRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVyZXJN
      U1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZh
      Y3R1cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVm
      YWN0dXJlck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5zEqoWCgpjYXJyaWVyTVNQEpsWGrcUCgNNU1ASrxQS
      pBQSoRQKCmNhcnJpZXJNU1AS5QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQjl6Q0NB
      WjZnQXdJQkFnSVVlS3BHK0pPWUVGRkRMWWZaQ3BYdm9LY3lyUk13Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFX
      VnlMVzVsZERBZUZ3MHkKTVRFeU1qRXdNalV3TURaYUZ3MHlOREV3TVRBd01qVXdNRFphTUZveEN6
      QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJt
      UnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNp
      MXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFUODY4czRuS0tmSXVtWHlF
      ODlxVEVkT1hQejN5N1F5UEs3dEs2QURYL1lXNFkyOTNDWnhFWnRqaUsxbXZnbQpXV2VWdXk4QkJX
      alNCV3A0VnNFUmhxREVvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93
      UUVBd0lCcGpBZEJnTlZIUTRFRmdRVUZiVzYreTJ0TzZjc3pLNXhyNFZBbFEzSEE3b3dDZ1lJS29a
      SXpqMEUKQXdJRFJ3QXdSQUlnSmd1QzI1ZFJhcXdhSEQ3STZXV1dDc3hwMmlZbmZpYUszMFZRSGFv
      bERxOENJQzZ5Y21XMApITFplQVRRVldqUXJMVUppV3gxYk0vNjZIMHVJTU82dVpZMloKLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoisggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdU
      Q0NBcE9nQXdJQkFnSVVIeWY2SjNmd2ZlSmgzZS9VK3VkbkFjVVNUNGN3Q2dZSUtvWkl6ajBFQXdJ
      dwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3
      R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhK
      eWFXVnlMVzVsZERBZUZ3MHkKTVRFeU1qRXdNalUzTURCYUZ3MHlNakV5TWpFd016QXlNREJhTUhn
      eEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0
      eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hN
      SFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdj
      cWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVElDRkJkREZxM09zeGc3NnNXVCtMYQp4YzlGSzRu
      bXRsL1hEMWIxcVhVTzY0RHpUdkxjaHp4NVI1ZkVyVlV2YjZYS3lGV05GWTMraGRhSXFRenROWHVI
      Cm80SUJGekNDQVJNd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlE
      VlIwT0JCWUUKRkxaZ3VXWXYwTlRPNlQ3Y0JUZVE0a1hhNkdpMk1COEdBMVVkSXdRWU1CYUFGQlcx
      dXZzdHJUdW5MTXl1Y2ErRgpRSlVOeHdPNk1DTUdBMVVkRVFRY01CcUNHR05oTFhSdmIyeHpMVFkx
      T0RrM1pHSTNOaTFvYTNOdWNUQ0JqUVlJCktnTUVCUVlIQ0FFRWdZQjdJbUYwZEhKeklqcDdJbUZp
      WVdNdWFXNXBkQ0k2SW5SeWRXVWlMQ0poWkcxcGJpSTYKSW5SeWRXVWlMQ0pvWmk1QlptWnBiR2xo
      ZEdsdmJpSTZJbU5oY25KcFpYSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MApTVVFpT2lKQlpHMXBia0Jq
      WVhKeWFXVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxCmhrak9QUVFE
      QWdOSUFEQkZBaUVBOUVkZGI5dmo2a2pJUk41T2xlZFlXSUtna1o4ajRVMjh0RlhvUC9QY3kwTUMK
      SUI3bVN3UHMyc1NtS1R2Tk9YcVh5NkxVM3RHenRnbHB2V3ZsY3dYaW5ZUmkKLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SuUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUI5ekNDQVo2Z0F3SUJBZ0lVZUtwRytKT1lFRkZETFlmWkNwWHZvS2N5clJNd0NnWUlL
      b1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBN
      QTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUURE
      QTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1URXlNakV3TWpVd01EWmFGdzB5TkRFd01UQXdN
      alV3TURaYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5C
      Z05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09Z
      MkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBVDg2
      OHM0bktLZkl1bVh5RTg5cVRFZE9YUHozeTdReVBLN3RLNkFEWC9ZVzRZMjkzQ1p4RVp0amlLMW12
      Z20KV1dlVnV5OEJCV2pTQldwNFZzRVJocURFbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01B
      NEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVGYlc2K3kydE82Y3N6SzV4cjRWQWxR
      M0hBN293Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJZ0pndUMyNWRSYXF3YUhEN0k2V1dXQ3N4cDJp
      WW5maWFLMzBWUUhhb2xEcThDSUM2eWNtVzAKSExaZUFUUVZXalFyTFVKaVd4MWJNLzY2SDB1SU1P
      NnVaWTJaCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgB
      EhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIe
      CAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIa
      EggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIG
      CAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9u
      UG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9B
      ZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1
      cmUSEBIGCP////8PGgZBZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1
      cHBseWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRp
      ZXMSFBIKCggKBFYyXzASABoGQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYa
      BkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcS
      DQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlu
      cyoGQWRtaW5zGg4KBAoCCgAKAAoACgAKAA==
