apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/SethuRamanOmanakuttan/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.3.1
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://10.251.4.130:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secret/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIC2frQaMK4A7c1tHerkjwVpIYePrQK6A0mm5M/UYLrAYEpxeCpleCpZeCngKWggBEAEaBgj4
      lIOOBiIKc3lzY2hhbm5lbCpAMWNmMjBkYWExMzg2NTdiYTFmZTczNzU5MDI2MzNjNDA2NmRmNTBi
      NWQyNzU5OTc4MjY1OGQyNGNmNmZlMTI5ZhIaEhhf9FVBs+OXMQuLDLrFyGDknDbxT+LghngSmV0K
      ll0Sk10SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVVTVpcGVKU084ZzlRR3M5RzhjeVJ4bEJla3lvd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05NakV4TWpJd01UZ3hNakkwV2hjTk1qUXhNREE1TVRneE1qSTBX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJDdkF0
      WTNQb0VtU2hXWk5TQTBZdTlYa0JhdDZNeGxabVEwNStWekVUSC9IVjdub2NtTjEKSUdJWnpXNmRk
      dHZPV2RLTWRNMXRoUzI2SGFJQ1E2ZWY0UGlqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUmt3cFFERlgwS0tmT2JtZVB5bXJNbTh3
      Z1BzVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQTRlWXBrb21mNU41NnlhUXBTY0hvUmRFT211
      T2dKTU9RUm03WnNPeDAKQWpNQ0lFVkJnK0szMWJpN2M5am43emJlVm9jUmRGSnlpc1I0V3VHUWdD
      YksxTE5aCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVQTZ5U3NQOFNCNk5jY3Blc3FTZElFOVBJbFIwd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NakV4TWpJd01UZ3hOakF3V2hjTk1q
      SXhNakl3TVRneU1UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFRnhVdU93eGFiRm1OK1FRdU1TMzhlMGpiaFpl
      TG9scEwKNFhBeTluUzdqQzlja3lhVlRncjFmZ2FGcmxUTURmVUd5Z01IbGNRMy9nMy9BL0tlcHAz
      WFVLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRT3VSK0F1b0I1ClJvS20rMkZyWEExZkRUaGdWakFmQmdOVkhTTUVHREFXZ0JS
      a3dwUURGWDBLS2ZPYm1lUHltck1tOHdnUHNUQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M04yTTVOR1kyWkdNM0xYTm5aalUyTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnVm1ic1J2QzRqNHkxY3RxVGZFb0kzWE10QjFtOEEzYW5UUGNKY2g4K01Gb0NJQ2hC
      cTd1SGFmaGNLRkhxCnp5bncxTVdZVVE2TEczYjVnY1o2anZXb0hqNXgKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVVTVpcGVKU084ZzlRR3M5RzhjeVJ4bEJla3lvd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NakV4TWpJd01UZ3hNakkwV2hjTk1qUXhNREE1
      TVRneE1qSTBXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJDdkF0WTNQb0VtU2hXWk5TQTBZdTlYa0JhdDZNeGxabVEwNStWekVUSC9IVjdub2NtTjEK
      SUdJWnpXNmRkdHZPV2RLTWRNMXRoUzI2SGFJQ1E2ZWY0UGlqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUmt3cFFERlgwS0tmT2Jt
      ZVB5bXJNbTh3Z1BzVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQTRlWXBrb21mNU41NnlhUXBT
      Y0hvUmRFT211T2dKTU9RUm03WnNPeDAKQWpNQ0lFVkJnK0szMWJpN2M5am43emJlVm9jUmRGSnlp
      c1I0V3VHUWdDYksxTE5aCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2Fw
      YWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxqMEgoNQ29uc2Vuc3VzVHlwZRL6ERLvEQoI
      ZXRjZHJhZnQS4hEKyxEKGm9yZGVyZXIxLmRldmVsb3AubG9jYWwuY29tEPtBGtMILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQXFtZ0F3SUJBZ0lVVUphT004TG01YmZHRloxK3I0
      ZFczM3k3eVdjd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNt
      VnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NakV4TWpJd01U
      Z3hOakF3V2hjTk1qSXhNakl3TVRneU1UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0Ex
      VUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJB
      dwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3Ykhs
      amFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUnQxQS9ZbHhM
      ZXZnNVpHMGN2Y1RtTnhVakkKN1ZiNnQ1ekN1aDlGcDZoT2VtbllyL0VoNnlFNkdVMFljSG5GWG5a
      VERWamhINnhuNGhTZUNjTlBYSU1rbzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIw
      R0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUSt1WWZyZXBZSm10VDlmdks3UjVyWnpSMzIKaWpBZkJnTlZIU01FR0RB
      V2dCUmt3cFFERlgwS0tmT2JtZVB5bXJNbTh3Z1BzVEEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1
      ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1
      SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmho
      YVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBd1JRSWhBT3JnOW1IVGF0MXNUbzVFCis2SEF1aXNaNEtpZW9FZVgwZGZORi9IVnRwb0dBaUJs
      U1JSMEdCTjdhRFVzeUkzRDlXK0pZNXBNakcvSUtsZUEKdkV5VEp5NDVxQT09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQXFt
      Z0F3SUJBZ0lVVUphT004TG01YmZHRloxK3I0ZFczM3k3eVdjd0NnWUlLb1pJemowRUF3SXcKWGpF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxq
      YUdGcGJpMXVaWFF3CkhoY05NakV4TWpJd01UZ3hOakF3V2hjTk1qSXhNakl3TVRneU1UQXdXakJ4
      TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1
      TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lE
      VlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQ0FBUnQxQS9ZbHhMZXZnNVpHMGN2Y1RtTnhVakkKN1ZiNnQ1ekN1aDlG
      cDZoT2VtbllyL0VoNnlFNkdVMFljSG5GWG5aVERWamhINnhuNGhTZUNjTlBYSU1rbzRJQgpNREND
      QVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JC
      Z0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUSt1WWZyZXBZSm10VDlm
      dks3UjVyWnpSMzIKaWpBZkJnTlZIU01FR0RBV2dCUmt3cFFERlgwS0tmT2JtZVB5bXJNbTh3Z1Bz
      VEEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXla
      R1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBk
      SEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJ
      am9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXla
      R1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBT3JnOW1IVGF0MXNUbzVFCis2SEF1
      aXNaNEtpZW9FZVgwZGZORi9IVnRwb0dBaUJsU1JSMEdCTjdhRFVzeUkzRDlXK0pZNXBNakcvSUts
      ZUEKdkV5VEp5NDVxQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAF
      KICAgAgaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9j
      a1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoH
      UmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1p
      bnMSuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4SsRcKD21h
      bnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0N6Q0NBYktnQXdJQkFnSVVRV1hwZDEvMlN6ckhl
      TW1ia1RubUJQMFR6cjh3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5Z
      VzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdI
      aGNOTWpFeE1qSXdNVGd4TkRJMldoY05NalF4TURBNU1UZ3hOREkyV2pCa01Rc3dDUVlEVlFRRwpF
      d0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJn
      TlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNt
      VnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJQaVkvclhaY1JVZzJX
      Ynk1dS9SS2Z2cWJhR0xSOUltWHBYRgppQzlGeDF0YjhDandEc1BWWFFnaWZCbXdaTmhiSzFxSERM
      aFhDbWwrLzNOUXlBamZpQStqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFR
      SC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUWtFTS9GMFJMNm81enAKUUx3eUU0MzZOOHc0L2pBS0Jn
      Z3Foa2pPUFFRREFnTkhBREJFQWlCR04xRFYyenhRdEhZZm1DN1BKSHlKZkQyMgpaYXJRN0ZscVFm
      cWRnVWlPK2dJZ0UyM1hKd00xQ0dDcXlUSHI3Y0RGenlJVGs4bVN3NmFXVDZDdU9yd1JkcEU9Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SURFVENDQXJlZ0F3SUJBZ0lVSXVoUGttNnVpM09HQU9qKzVMNVJNbCszWnhFd0NnWUlLb1pJemow
      RUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFV
      RUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFN
      TUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qRXhNakl3TVRneE9EQXdXaGNOTWpJ
      eE1qSXdNVGd5TXpBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEzTGpN
      NEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFNQmdO
      VkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFEREJa
      QlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkKemow
      REFRY0RRZ0FFWkJCT2VMUGhGODJWVGdPMUdlNVVrczlydFdnN3N1ZlVuck5tSjJpT0ZodTJGNHdy
      dWRCcQpJeVpjOHVvd2pvRWNuUUphL004VVQ5TVJXT1lnQVNmcU02T0NBU0l3Z2dFZU1BNEdBMVVk
      RHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJRTUJXK0t4d1hJ
      WlZoOTNMYWZhdS9meXlKallUQWYKQmdOVkhTTUVHREFXZ0JRa0VNL0YwUkw2bzV6cFFMd3lFNDM2
      Tjh3NC9qQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwNE5UaGpabVEwTnpnNExUYzFibTVq
      TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lkSEox
      WlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVkV1po
      WTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZM1Ix
      Y21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklB
      REJGCkFpRUF4aHdITmNIek11Q3ViSW5Vekc5bjNUMk0zSFBSNzFRNGpkV3hmbTl0WVZFQ0lBVGg1
      RzlSRC8xZU1jbXcKR1lvREsyemMvbURhaEJyUTU1UDBZckg0dDMveAotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQ0N6Q0NBYktnQXdJQkFnSVVRV1hwZDEvMlN6ckhlTW1ia1RubUJQMFR6cjh3Q2dZSUtvWkl6
      ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZC
      QU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpFeE1qSXdNVGd4TkRJMldoY05N
      alF4TURBNU1UZ3hOREkyV2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlh
      V05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxj
      akVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlB
      Z0VHQ0NxR1NNNDlBd0VIQTBJQUJQaVkvclhaY1JVZzJXYnk1dS9SS2Z2cWJhR0xSOUltWHBYRgpp
      QzlGeDF0YjhDandEc1BWWFFnaWZCbXdaTmhiSzFxSERMaFhDbWwrLzNOUXlBamZpQStqUWpCQU1B
      OEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JC
      UWtFTS9GMFJMNm81enAKUUx3eUU0MzZOOHc0L2pBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCR04x
      RFYyenhRdEhZZm1DN1BKSHlKZkQyMgpaYXJRN0ZscVFmcWRnVWlPK2dJZ0UyM1hKd00xQ0dDcXlU
      SHI3Y0RGenlJVGs4bVN3NmFXVDZDdU9yd1JkcEU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      GgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1T
      UBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJN
      U1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVyZXJN
      U1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZh
      Y3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoDTVNQErcUEqwU
      EqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2
      Z0F3SUJBZ0lVS2pBUWxHWHcreXFlSEF1eHhYdXpHWTNnNjl3d0NnWUlLb1pJemowRUF3SXcKV2pF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5
      TFc1bGREQWVGdzB5Ck1URXlNakF4T0RFMk16TmFGdzB5TkRFd01Ea3hPREUyTXpOYU1Gb3hDekFK
      QmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2
      YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1
      WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBVDJqTTZhT21XVGd1dm1oMnEv
      cTdCdHlITTBrUjBWWThBTmxNS1Y5ZXJmdDlyOWZpYmpnMmJBWG5TdmhJdU4KTU9zM2tKZUlKRW1m
      Zlp1Q2ZmSElEZnhsbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FF
      QXdJQnBqQWRCZ05WSFE0RUZnUVVXZ0VyRUtubEtSTWt1c29qVS9ObFpzaEg2cUF3Q2dZSUtvWkl6
      ajBFCkF3SURTQUF3UlFJaEFNTEZNVG10R3h4S2szcUVzOTRIZ1VodWdyeG5iOUdyb0ZWY2RGL1BO
      YVhlQWlBcmVZMXQKVHpQZDFSVkdHSEZ2MEVtekNYNkNPakx5cHM0eWRDYWFwaHAwcXc9PQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      N1RDQ0FwT2dBd0lCQWdJVVgrUWR2VHJ4T25DZzR0em9JL012MmM3V3VPNHdDZ1lJS29aSXpqMEVB
      d0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZ
      WEp5YVdWeUxXNWxkREFlRncweQpNVEV5TWpBeE9ESXdNREJhRncweU1qRXlNakF4T0RJMU1EQmFN
      SGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWti
      MjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVD
      eE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRC
      Z2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSMHRIOGtsY3YzYVU2RmNuTisrd3pxCnlrQWh2
      TlNHbWw5NEpjSytPUFZndk1iQmlmcU85WTZyZjZkNEQ3aE0rbFBqeXE5bGl3SnZrRGluc2N0eTBh
      MDkKbzRJQkZ6Q0NBUk13RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hR
      WURWUjBPQkJZRQpGSEUraVA4aytBZytDckhIaUwyRTlnemQ0aHRNTUI4R0ExVWRJd1FZTUJhQUZG
      b0JLeENwNVNrVEpMcktJMVB6ClpXYklSK3FnTUNNR0ExVWRFUVFjTUJxQ0dHTmhMWFJ2YjJ4ekxU
      WTFPRGszWkdJM05pMXhiRGsyYkRDQmpRWUkKS2dNRUJRWUhDQUVFZ1lCN0ltRjBkSEp6SWpwN0lt
      RmlZV011YVc1cGRDSTZJblJ5ZFdVaUxDSmhaRzFwYmlJNgpJblJ5ZFdVaUxDSm9aaTVCWm1acGJH
      bGhkR2x2YmlJNkltTmhjbkpwWlhJaUxDSm9aaTVGYm5KdmJHeHRaVzUwClNVUWlPaUpCWkcxcGJr
      QmpZWEp5YVdWeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3EKaGtqT1BR
      UURBZ05JQURCRkFpRUEvYWtNdGJHQm1hRWErek5iVE9OUGRHZ2FXcnE3eDdTeDdZbGNBUmJ2SU93
      QwpJRzJ2VDBVcXNLRHY5U1NTMFdHenlwRFVaakxYQWxyTWU3bGIyQlB2RUlEVAotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVLakFRbEdYdyt5cWVIQXV4eFh1ekdZM2c2OXd3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFR
      RERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTVRFeU1qQXhPREUyTXpOYUZ3MHlOREV3TURr
      eE9ERTJNek5hTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpB
      TkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3
      T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFU
      MmpNNmFPbVdUZ3V2bWgycS9xN0J0eUhNMGtSMFZZOEFObE1LVjllcmZ0OXI5ZmliamcyYkFYblN2
      aEl1TgpNT3Mza0plSUpFbWZmWnVDZmZISURmeGxvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgv
      TUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVVdnRXJFS25sS1JNa3Vzb2pVL05s
      WnNoSDZxQXdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQU1MRk1UbXRHeHhLazNxRXM5NEhnVWh1
      Z3J4bmI5R3JvRlZjZEYvUE5hWGVBaUFyZVkxdApUelBkMVJWR0dIRnYwRW16Q1g2Q09qTHlwczR5
      ZENhYXBocDBxdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoLRW5kb3Jz
      ZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVhZGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIc
      EggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMS
      OhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3Jp
      dGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI
      /////w8aBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0
      ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIa
      BkFkbWlucyoGQWRtaW5zGg4KBAoCCgAKAAoACgAKAA==
