apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/SethuRamanOmanakuttan/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.3.1
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://10.251.4.130:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secret/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIOUWsMjvaS9ofdj0C4e3/bOMqNNWzdfflk+nFaNJk9llEpxeCpleCpZeCngKWggBEAEaBgiO
      qYWOBiIKc3lzY2hhbm5lbCpAZmQyYTFjZjY2OWJiZWY0NGQ0Mjk3ZmE4YTRhMjJkOGQwY2U5Mzc5
      MjYzYjIzZjlhYzg0MjZjODQ1ODc4MjI3MxIaEhh1/IPQKzsMcEcpWDwiPBaYLv/2uK+/tSASmV0K
      ll0Sk10SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVUit4N29zaEZOSjZwK1ArUUhmdlhXanVyeDNzd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05NakV4TWpJeE1ETTFOekEwV2hjTk1qUXhNREV3TURNMU56QTBX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJBTFFD
      OGwzVmhWUkwvQVd0VnEwWDlmV3p6MkREV2oveXFhTVRNR1NCdEpQU1RxRll3WXkKUFB2ejBXWS9R
      eTRqLzZSS1oxQTRMN1ErdEQ3Z00xb2Nzc2VqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0tNYWM2OUZsUUtmZ2NLRGNhVjNlTjk1
      a1Q5REFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQWo4ZWhoRUt5dWxFQXlGZ0R0UnVkMjVoa0dz
      RkdZY0FNTGdvbFBQREUKSzU0Q0lIODRwNi96bFd5OHpOOWFwNlVRU3k2aHdndHQ1NCtlQ1FnY0tX
      ZU1memNuCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVS1RDQ3czNXBna0oyWTBKVG11VE13V1Y1eVlvd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NakV4TWpJeE1EUXdOVEF3V2hjTk1q
      SXhNakl4TURReE1EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFV3pBQWRDdUc3RCtySzN2QW1UcXZ0MXdQVEwz
      T3JIYnQKREFCM21QbGZ2SEl5THJDeWIwNHVMa1lMVWUxVUJTTjl3dHZoM1BndUEyTVBWWnEvcG1q
      RFpxT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSaDQyMDltVDltCkFCb3FuSkxpNmlZL1NvaXp4akFmQmdOVkhTTUVHREFXZ0JT
      S01hYzY5RmxRS2ZnY0tEY2FWM2VOOTVrVDlEQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M04yTTVOR1kyWkdNM0xXNTRPV2RpTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnU3ZjbVBYdDc1eklDTVpuSGI3dWJ6UnphM0JRQzJSZlRFY1MwRUgrcmpSOENJRy80
      VWNkMHNBTG5XVGc0Ckp1N1FkMTZxRW5yaUgwUW1LdXUyc0tKcEpkZFUKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVUit4N29zaEZOSjZwK1ArUUhmdlhXanVyeDNzd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NakV4TWpJeE1ETTFOekEwV2hjTk1qUXhNREV3
      TURNMU56QTBXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJBTFFDOGwzVmhWUkwvQVd0VnEwWDlmV3p6MkREV2oveXFhTVRNR1NCdEpQU1RxRll3WXkK
      UFB2ejBXWS9ReTRqLzZSS1oxQTRMN1ErdEQ3Z00xb2Nzc2VqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0tNYWM2OUZsUUtmZ2NL
      RGNhVjNlTjk1a1Q5REFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQWo4ZWhoRUt5dWxFQXlGZ0R0
      UnVkMjVoa0dzRkdZY0FNTGdvbFBQREUKSzU0Q0lIODRwNi96bFd5OHpOOWFwNlVRU3k2aHdndHQ1
      NCtlQ1FnY0tXZU1memNuCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2Fw
      YWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxqMEgoNQ29uc2Vuc3VzVHlwZRL6ERLvEQoI
      ZXRjZHJhZnQS4hEKyxEKGm9yZGVyZXIxLmRldmVsb3AubG9jYWwuY29tEPtBGtMILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQXFtZ0F3SUJBZ0lVS3YyQnprbHJFUUxlaHZpWWZQ
      YTd5RFhIQ2NVd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNt
      VnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NakV4TWpJeE1E
      UXdOVEF3V2hjTk1qSXhNakl4TURReE1EQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0Ex
      VUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJB
      dwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3Ykhs
      amFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUmF2OFZkeEFa
      SklPYXVFUlpMdzVxMGtTblYKeTdJN0s0ZFlidktGelJlUUM5QW1kUm1MdXRhZVl0ZXlUT1NBVEti
      a1lIemhBdUYxOFJYV3k2aFd4b2UybzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIw
      R0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUUdPbUpyZFhvTiswQ3NOTHNIUlBBUlE4OXAKVlRBZkJnTlZIU01FR0RB
      V2dCU0tNYWM2OUZsUUtmZ2NLRGNhVjNlTjk1a1Q5REEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1
      ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1
      SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmho
      YVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBd1JRSWhBT3ZuL3I0NFJ2QjZoUnA0Cm1ZT1FVRHg1bG5jckU3WDFtblRiaDE5aGxRM1dBaUFD
      N1cyRVZWcXRZRXNhQTFSRHdxaTRZbXRKNkVyTEM1K0IKeGhoaFJtZTQ1Zz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQXFt
      Z0F3SUJBZ0lVS3YyQnprbHJFUUxlaHZpWWZQYTd5RFhIQ2NVd0NnWUlLb1pJemowRUF3SXcKWGpF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxq
      YUdGcGJpMXVaWFF3CkhoY05NakV4TWpJeE1EUXdOVEF3V2hjTk1qSXhNakl4TURReE1EQXdXakJ4
      TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1
      TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lE
      VlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQ0FBUmF2OFZkeEFaSklPYXVFUlpMdzVxMGtTblYKeTdJN0s0ZFlidktG
      elJlUUM5QW1kUm1MdXRhZVl0ZXlUT1NBVEtia1lIemhBdUYxOFJYV3k2aFd4b2UybzRJQgpNREND
      QVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JC
      Z0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUUdPbUpyZFhvTiswQ3NO
      THNIUlBBUlE4OXAKVlRBZkJnTlZIU01FR0RBV2dCU0tNYWM2OUZsUUtmZ2NLRGNhVjNlTjk1a1Q5
      REEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXla
      R1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBk
      SEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJ
      am9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXla
      R1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBT3ZuL3I0NFJ2QjZoUnA0Cm1ZT1FV
      RHg1bG5jckU3WDFtblRiaDE5aGxRM1dBaUFDN1cyRVZWcXRZRXNhQTFSRHdxaTRZbXRKNkVyTEM1
      K0IKeGhoaFJtZTQ1Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAF
      KICAgAgaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9j
      a1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoH
      UmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1p
      bnMSuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4SsRcKD21h
      bnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0N6Q0NBYktnQXdJQkFnSVViN3E0VFByUUxZT2JG
      VmpPVjN6N3VRQ2h6TUV3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5Z
      VzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdI
      aGNOTWpFeE1qSXhNRE0xT1RBMVdoY05NalF4TURFd01ETTFPVEExV2pCa01Rc3dDUVlEVlFRRwpF
      d0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJn
      TlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNt
      VnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFRnF2MlRLTFJHb0cr
      RG1nQUpudWhqVXFwNjFleFczQzRWaApySUxDT3dhK2xGNTFKaVFLazAxVFEzZkloTkFPaGsxR2tp
      ZXhrWmtwZmNad2hOTVNhZldqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFR
      SC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUi82UEpma2hRanFHb0YKditNZ2VjVU9tM2lZc3pBS0Jn
      Z3Foa2pPUFFRREFnTkhBREJFQWlCbDVsUS96Y2I0eHViY1VyV2pYakJ3ZmVqcgpuQllabEcrQ1F6
      VTZGWGZOeXdJZ0oxc2llTmxwZFpMNFRGclZTV2wza0U4eGpyNW8xMld1NlJyR1ZWd2hoaWs9Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SURFRENDQXJlZ0F3SUJBZ0lVQnVVREQvNnU1UmxPUEFvRGt1eFZxZHdNUlNBd0NnWUlLb1pJemow
      RUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFV
      RUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFN
      TUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qRXhNakl4TURRd05qQXdXaGNOTWpJ
      eE1qSXhNRFF4TVRBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEzTGpN
      NEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFNQmdO
      VkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFEREJa
      QlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkKemow
      REFRY0RRZ0FFZ1dKZ0h0SkpxUi9vUU1ybVVNNUJ1ZjVYY3E3dHJnUnFwOStlMkl5M2RJbUQxL1N3
      YXR3MQppaVNSeU55T1N2OTBXQVZ1dkJrekFtalQ4QkpRbHpaakVLT0NBU0l3Z2dFZU1BNEdBMVVk
      RHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJSUTFRa3RoZncr
      aU0vYjlJMjF6elpKT1krcm5UQWYKQmdOVkhTTUVHREFXZ0JSLzZQSmZraFFqcUdvRnYrTWdlY1VP
      bTNpWXN6QWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwNE5UaGpabVEwTnpnNExYWTVlbXQ2
      TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lkSEox
      WlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVkV1po
      WTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZM1Ix
      Y21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTkhB
      REJFCkFpQVRRNEk4Yy9qYzB0QVJZc3lKdlVNRS9mVm1UZElPR3VRaHJZTUMyenNzMFFJZ1FETmV2
      aWFLK1hzSTNGYzkKNnlpS2hsMGt5OW55N1IvcWI1L200M29ydnpZPQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQ0N6Q0NBYktnQXdJQkFnSVViN3E0VFByUUxZT2JGVmpPVjN6N3VRQ2h6TUV3Q2dZSUtvWkl6
      ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZC
      QU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpFeE1qSXhNRE0xT1RBMVdoY05N
      alF4TURFd01ETTFPVEExV2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlh
      V05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxj
      akVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlB
      Z0VHQ0NxR1NNNDlBd0VIQTBJQUJFRnF2MlRLTFJHb0crRG1nQUpudWhqVXFwNjFleFczQzRWaApy
      SUxDT3dhK2xGNTFKaVFLazAxVFEzZkloTkFPaGsxR2tpZXhrWmtwZmNad2hOTVNhZldqUWpCQU1B
      OEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JC
      Ui82UEpma2hRanFHb0YKditNZ2VjVU9tM2lZc3pBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCbDVs
      US96Y2I0eHViY1VyV2pYakJ3ZmVqcgpuQllabEcrQ1F6VTZGWGZOeXdJZ0oxc2llTmxwZFpMNFRG
      clZTV2wza0U4eGpyNW8xMld1NlJyR1ZWd2hoaWs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      GgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1
      cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0
      dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0
      dXJlck1TUBABGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoDTVNQErcUEqwU
      EqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrVENDQVo2
      Z0F3SUJBZ0lVRUVGU2FZaW9vNUF1NmY3VG90cklaYTdGSXBnd0NnWUlLb1pJemowRUF3SXcKV2pF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5
      TFc1bGREQWVGdzB5Ck1URXlNakV3TkRBeE1URmFGdzB5TkRFd01UQXdOREF4TVRGYU1Gb3hDekFK
      QmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2
      YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1
      WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUlBUOWNMaGdBbjNFNzM5bnNw
      UFh0RHZTOXhkS2hWd05yci9raThXZTZQdE1PaUFjOFpsams1RWk2ZWFORlMKaXF5SFJSWHJNNWpG
      VkdsblAwd2lxcTRMbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FF
      QXdJQnBqQWRCZ05WSFE0RUZnUVV0S2F2Sk5jYWRBWU8xQ1VGcUJ5TjhQSlNhZVl3Q2dZSUtvWkl6
      ajBFCkF3SURTUUF3UmdJaEFJWWZ0Qlo1bmlrUkEyQXEzNG5HSUtzZnl4WVA4ei9mTFlwSklzZWFi
      eVd5QWlFQXhLWWsKQUhjcUsyYTlHSk1aelJWSlFSUzhqNHlCMGFmcnFDYnUxcVhucGtNPQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      N0RDQ0FwT2dBd0lCQWdJVWJPbDFueTJ5ZWxlQkJ0d00xd01iaEJiUDg4Y3dDZ1lJS29aSXpqMEVB
      d0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZ
      WEp5YVdWeUxXNWxkREFlRncweQpNVEV5TWpFd05EQTRNREJhRncweU1qRXlNakV3TkRFek1EQmFN
      SGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWti
      MjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVD
      eE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRC
      Z2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSelVKaC9zZHUySm9HeW1hYmhoK3ZrCkhVVFVT
      cEt0UEF6LzhjbDJuZ0xjWGZ1RjgvbmpvMEIva0ZvZkpEcWJKWEtPTEVleUk5UFBMbkdRQXV5MlpZ
      TlAKbzRJQkZ6Q0NBUk13RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hR
      WURWUjBPQkJZRQpGQVRmeTJ4THVIWmZoYWhHSExaMVV1bXB4bVZxTUI4R0ExVWRJd1FZTUJhQUZM
      U21yeVRYR25RR0R0UWxCYWdjCmpmRHlVbW5tTUNNR0ExVWRFUVFjTUJxQ0dHTmhMWFJ2YjJ4ekxU
      WTFPRGszWkdJM05pMDFaSGhpYXpDQmpRWUkKS2dNRUJRWUhDQUVFZ1lCN0ltRjBkSEp6SWpwN0lt
      RmlZV011YVc1cGRDSTZJblJ5ZFdVaUxDSmhaRzFwYmlJNgpJblJ5ZFdVaUxDSm9aaTVCWm1acGJH
      bGhkR2x2YmlJNkltTmhjbkpwWlhJaUxDSm9aaTVGYm5KdmJHeHRaVzUwClNVUWlPaUpCWkcxcGJr
      QmpZWEp5YVdWeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3EKaGtqT1BR
      UURBZ05IQURCRUFpQTNFYzh4UENrNE5EMDNISGlZSlU1UTl4UUVDQllzK3NPNDB5T055dFRVUGdJ
      ZwpRS25MSjhJYm5KWjRmbGhaME5uWmVzQkV5MDA1VUV1OGtmaWhJZFJnL3J3PQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQitUQ0NBWjZnQXdJQkFnSVVFRUZTYVlpb281QXU2ZjdUb3RySVphN0ZJcGd3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFR
      RERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTVRFeU1qRXdOREF4TVRGYUZ3MHlOREV3TVRB
      d05EQXhNVEZhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpB
      TkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3
      T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFS
      UFQ5Y0xoZ0FuM0U3Mzluc3BQWHREdlM5eGRLaFZ3TnJyL2tpOFdlNlB0TU9pQWM4WmxqazVFaTZl
      YU5GUwppcXlIUlJYck01akZWR2xuUDB3aXFxNExvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgv
      TUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVXRLYXZKTmNhZEFZTzFDVUZxQnlO
      OFBKU2FlWXdDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0loQUlZZnRCWjVuaWtSQTJBcTM0bkdJS3Nm
      eXhZUDh6L2ZMWXBKSXNlYWJ5V3lBaUVBeEtZawpBSGNxSzJhOUdKTVp6UlZKUVJTOGo0eUIwYWZy
      cUNidTFxWG5wa009Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoGQWRtaW5z
      EioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1l
      bnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVhZGVycxIo
      Eh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMS
      OhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3Jp
      dGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI
      /////w8aBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1p
      bnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMa
      BkFkbWlucyoGQWRtaW5zGg4KBAoCCgAKAAoACgAKAA==
